---

- name: install package on centos
  include: centos.yml
  when: ansible_distribution == "CentOS"

- name: install package on debian
  include: debian.yml
  when: ansible_distribution == "Debian"

- name: install gem plugins
  gem:
    name: "{{ item }}"
    executable: /opt/td-agent/embedded/bin/fluent-gem
    state: latest
    user_install: no
  with_items: "{{ fluentd_plugins }}"
  notify:
    - restart fluentd
  tags: fluentd_plugins

- name: ensure config dir exists
  file:
    path: "{{ fluentd_config_path }}/conf.d"
    state: directory
    owner: "{{ fluentd_user }}"
    group: "{{ fluentd_usergroup }}"
    mode: 0744
  tags: fluentd_config

- name: ensure log dir exists and is writable
  file:
    path: "{{ fluentd_log_path }}"
    state: directory
    owner: "{{ fluentd_user }}"
    group: "{{ fluentd_usergroup }}"
    mode: 0744
  tags: fluentd_config

- name: config
  template:
    src: "{{ item }}.j2"
    dest: "{{ fluentd_config_path }}/{{ item }}"
    owner: "{{ fluentd_user }}"
    group: "{{ fluentd_usergroup }}"
    mode: 0644
  with_items:
    - conf.d/filter.conf
    - conf.d/match.conf
    - conf.d/source.conf
    - conf.d/system.conf
    - td-agent.conf
  notify:
    - restart fluentd
  tags: fluentd_config

- name: service start
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ fluentd_daemon }}"
