############
# CentOS 7 #
############
Vagrant.configure(2) do | config |
  config.ssh.insert_key = false
  config.ssh.username = 'vagrant'
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  config.vm.define "centos7" do |centos7|
    centos7.vm.hostname = "centos7.dev"
    centos7.vm.box = "geerlingguy/centos7"
    centos7.vm.network :private_network, ip: "192.168.40.4"

    # Ansible
    config.vm.provision "ansible" do |ansible|

      ansible.sudo = true
      ansible.playbook = "test.yml"
    end
  end
end
